apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  namespace: app # Specify the namespace if needed
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: abdelrahmansayed/my-app:v1.0 # Replace with your actual image
        ports:
        - containerPort: 5000
