apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: app # Specify the namespace if needed
spec:
  selector:
    app: frontend
  ports:
    - protocol: TCP
      port: 9900           # The port that the service exposes
      targetPort: 5000   # The port on the container that the service should forward traffic to
  type: ClusterIP       # The type of service. Can also be NodePort or LoadBalancer depending on your needs
